title: Filip Švehla
email: filip@svehla.cloud
description: >-
  Oficiální web Filipa Švehly, mladého tradera a mentora
baseurl: ""  # žádný podadresář
url: "https://svehla.cloud"
theme: jekyll-theme-cayman
