title: Filip Švehla
email: filip@svehla.cloud
description: >- 
  Oficiální web Filipa Švehly, mladého tradera a mentora.
baseurl: "" # pokud bude na kořeni domény (např. svehla.cloud)
url: "https://svehla.cloud"

theme: jekyll-theme-cayman
